### PR TITLE
Feature/video view styling

### PR DESCRIPTION
**Pull request by Ruxton**
Adapted from https://codepen.io/souporserious/pen/KwpojY

See in action at https://ignite.digitalignition.net/kind/video/

### CODE REVIEW

**Comment by pfefferle** [comment]
sorry for the late reply :(

but why replacing the core video player?

**Comment by Ruxton** [comment]
@pfefferle Umm I don't remember, I'm sure I had a great reason when I did it.  I'll try it with the WP video code and see what the deal was..

**Comment by Ruxton** [comment]
@pfefferle So this was a styling thing.. I was just trying to make a video player that was more simplistic/fit with the style of the theme.

Standard WP
WP standard

Changed

**Comment by Ruxton** [comment]
See https://ignite.digitalignition.net/2018/09/10/98036/ I'll probably close this and replace it with a more up to date version built from current master.

**Pull request closed without merging**
